services:
  postgres:
    image: postgres:14
    container_name: pelephone-postgres
    environment:
      POSTGRES_USER: pelephone
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: pelephone_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pelephone-network

  redis:
    image: redis:6-alpine
    container_name: pelephone-redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-password}
    ports:
      - "6379:6379"
    networks:
      - pelephone-network
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  
networks:
  pelephone-network:
    driver: bridge